// <auto-generated />
using System.Collections.Generic;
using Automata.Core.Automation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Automata.Core.Automation.Data.Migrations
{
    [DbContext(typeof(AutomataDb))]
    [Migration("20260923145514_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Automata.Core.Automation.Data.DatasetRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Columns")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ModifiedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Datasets", (string)null);
                });

            modelBuilder.Entity("Automata.Core.Automation.Data.DatasetRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DatasetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId", "Ordinal");

                    b.ToTable("DatasetRows", (string)null);
                });

            modelBuilder.Entity("Automata.Core.Automation.Data.MetaEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Meta", (string)null);
                });

            modelBuilder.Entity("Automata.Core.Automation.Data.RunEventRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "TaskId");

                    b.ToTable("RunEvents", (string)null);
                });

            modelBuilder.Entity("Automata.Core.Automation.Data.RunOutputRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StepId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "TaskId");

                    b.ToTable("RunOutputs", (string)null);
                });

            modelBuilder.Entity("Automata.Core.Automation.Execution.ParkedRun", b =>
                {
                    b.Property<string>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Checkpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CollectionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ParkedAtUtc")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("RemainingTaskIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResumeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TasksPassed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalTasks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RunId");

                    b.ToTable("ParkedRuns", (string)null);
                });

            modelBuilder.Entity("Automata.Core.Automation.Model.Collection", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeletedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ModifiedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("TaskOrder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Settings", "Automata.Core.Automation.Model.Collection.Settings#EngineSettingsOverride", b1 =>
                        {
                            b1.Property<bool?>("AllowLlmRepair")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("BrowserProfile")
                                .HasColumnType("TEXT");

                            b1.Property<bool?>("ContinueOnStepError")
                                .HasColumnType("INTEGER");

                            b1.Property<bool?>("ContinueOnTaskError")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("DefaultStepTimeoutMs")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Discriminator")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("LlmProvider")
                                .HasColumnType("TEXT");

                            b1.Property<bool?>("ScreenshotOnFailure")
                                .HasColumnType("INTEGER");

                            b1.Property<bool?>("SelfHeal")
                                .HasColumnType("INTEGER");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Retry", "Automata.Core.Automation.Model.Collection.Settings#EngineSettingsOverride.Retry#RetryPolicy", b2 =>
                                {
                                    b2.Property<double>("BackoffMultiplier")
                                        .HasColumnType("REAL");

                                    b2.Property<int>("DelayMs")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("MaxAttempts")
                                        .HasColumnType("INTEGER");
                                });

                            b1.HasDiscriminator<string>("Discriminator").HasValue("EngineSettingsOverride");
                        });

                    b.HasKey("Id");

                    b.ToTable("Collections", (string)null);
                });

            modelBuilder.Entity("Automata.Core.Automation.Model.TaskDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CollectionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeletedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Inputs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ModifiedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Outputs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Demo", "Automata.Core.Automation.Model.TaskDefinition.Demo#DemoOrigin", b1 =>
                        {
                            b1.Property<string>("FactoryHash")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasColumnType("TEXT");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Settings", "Automata.Core.Automation.Model.TaskDefinition.Settings#EngineSettingsOverride", b1 =>
                        {
                            b1.Property<bool?>("AllowLlmRepair")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("BrowserProfile")
                                .HasColumnType("TEXT");

                            b1.Property<bool?>("ContinueOnStepError")
                                .HasColumnType("INTEGER");

                            b1.Property<bool?>("ContinueOnTaskError")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("DefaultStepTimeoutMs")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Discriminator")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("LlmProvider")
                                .HasColumnType("TEXT");

                            b1.Property<bool?>("ScreenshotOnFailure")
                                .HasColumnType("INTEGER");

                            b1.Property<bool?>("SelfHeal")
                                .HasColumnType("INTEGER");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Retry", "Automata.Core.Automation.Model.TaskDefinition.Settings#EngineSettingsOverride.Retry#RetryPolicy", b2 =>
                                {
                                    b2.Property<double>("BackoffMultiplier")
                                        .HasColumnType("REAL");

                                    b2.Property<int>("DelayMs")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("MaxAttempts")
                                        .HasColumnType("INTEGER");
                                });

                            b1.HasDiscriminator<string>("Discriminator").HasValue("EngineSettingsOverride");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("Automata.Core.Automation.Scheduling.ScheduleEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastOutcome")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastRunUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("NextDueUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Triggers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Schedule", (string)null);
                });

            modelBuilder.Entity("Automata.Core.Automation.Storage.AutomataSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BorderRadius")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PanelDetached")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PanelWindowHeight")
                        .HasColumnType("REAL");

                    b.Property<double?>("PanelWindowLeft")
                        .HasColumnType("REAL");

                    b.Property<double?>("PanelWindowTop")
                        .HasColumnType("REAL");

                    b.Property<double>("PanelWindowWidth")
                        .HasColumnType("REAL");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("SidebarWidth")
                        .HasColumnType("REAL");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "EngineDefaults", "Automata.Core.Automation.Storage.AutomataSettings.EngineDefaults#EngineSettingsOverride", b1 =>
                        {
                            b1.Property<bool?>("AllowLlmRepair")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("BrowserProfile")
                                .HasColumnType("TEXT");

                            b1.Property<bool?>("ContinueOnStepError")
                                .HasColumnType("INTEGER");

                            b1.Property<bool?>("ContinueOnTaskError")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("DefaultStepTimeoutMs")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Discriminator")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("LlmProvider")
                                .HasColumnType("TEXT");

                            b1.Property<bool?>("ScreenshotOnFailure")
                                .HasColumnType("INTEGER");

                            b1.Property<bool?>("SelfHeal")
                                .HasColumnType("INTEGER");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Retry", "Automata.Core.Automation.Storage.AutomataSettings.EngineDefaults#EngineSettingsOverride.Retry#RetryPolicy", b2 =>
                                {
                                    b2.Property<double>("BackoffMultiplier")
                                        .HasColumnType("REAL");

                                    b2.Property<int>("DelayMs")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("MaxAttempts")
                                        .HasColumnType("INTEGER");
                                });

                            b1.HasDiscriminator<string>("Discriminator").HasValue("EngineSettingsOverride");
                        });

                    b.HasKey("Id");

                    b.ToTable("Settings", (string)null);
                });

            modelBuilder.Entity("Automata.Core.Automation.Storage.RunManifest", b =>
                {
                    b.Property<string>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("EndedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RunId");

                    b.HasIndex("StartedUtc");

                    b.ToTable("Runs", (string)null);
                });

            modelBuilder.Entity("Automata.Core.Automation.Data.DatasetRow", b =>
                {
                    b.HasOne("Automata.Core.Automation.Data.DatasetRecord", null)
                        .WithMany("Rows")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Automata.Core.Automation.Data.RunEventRecord", b =>
                {
                    b.HasOne("Automata.Core.Automation.Storage.RunManifest", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Automata.Core.Automation.Data.RunOutputRecord", b =>
                {
                    b.HasOne("Automata.Core.Automation.Storage.RunManifest", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Automata.Core.Automation.Model.TaskDefinition", b =>
                {
                    b.HasOne("Automata.Core.Automation.Model.Collection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Automata.Core.Automation.Data.DatasetRecord", b =>
                {
                    b.Navigation("Rows");
                });
#pragma warning restore 612, 618
        }
    }
}
