// The injected scripts, checked against a real DOM and a real corpus of names.
//
//   node tools/verify-js.mjs [--keep]
//
// Nothing in Automata.Tests executes these files. FakeBrowserSurface answers a resolve with canned
// JSON, which proves the C# around the script and nothing about the script — so stability.js,
// fingerprint.js, resolver.js and harvest.js were, until this, only ever exercised by running the
// whole app and looking. That is how a filter that lets `ti6dpd` through survived: no check could
// have caught it, because no check ran the filter.
//
// Two halves, because the questions are different shapes:
//
//   1. Names. stability.js decides what is worth recording, and that decision is a pure function of
//      a string. Run in plain Node against a corpus of real ids and classes — the generated ones
//      taken from pages the acceptance profiles actually visited, the honest ones from this repo's
//      own fixtures and from the sites themselves. No browser needed, and it runs in milliseconds.
//
//   2. Elements. Everything else needs a DOM, so it gets one: the app is launched with its own CDP
//      ports and its own scratch store, the TARGET pane is pointed at a fixture, and the scripts are
//      evaluated in it exactly as the engine evaluates them. Driving the real WebView2 rather than a
//      Playwright-bundled Chromium is deliberate — it is the engine that actually ships, and
//      connectOverCDP needs no downloaded browser.

import { chromium } from 'playwright';
import { spawn, execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync, rmSync, readFileSync, existsSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..');
const scriptsDir = path.join(repoRoot, 'Automata.Core', 'Automation', 'Scripts');
const keep = process.argv.includes('--keep');

// Its own ports. verify-ui holds 9333-9336, and this must be runnable beside it.
const TARGET_PORT = 9337;
const PANEL_PORT = 9338;

const results = [];
function check(name, ok, detail) {
  results.push({ name, ok });
  console.log(`[${ok ? 'PASS' : 'FAIL'}] ${name}${ok || detail === undefined ? '' : ` — ${detail}`}`);
}
function group(name, fn) {
  try { fn(); check(name, true); }
  catch (err) { check(name, false, err.message); }
}
async function groupAsync(name, fn) {
  try { await fn(); check(name, true); }
  catch (err) { check(name, false, err.message); }
}
function assertTrue(value, message) { if (!value) throw new Error(message); }
function assertEqual(actual, expected, message) {
  if (actual !== expected) throw new Error(`${message} (expected ${expected}, got ${actual})`);
}
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

// ---- half one: names ---------------------------------------------------------------------------

/// stability.js assigns to `window`, so give it one. Nothing else in the file touches the DOM,
/// which is what makes this half runnable without a browser at all.
function loadStability() {
  const src = readFileSync(path.join(scriptsDir, 'stability.js'), 'utf8');
  const sandbox = { window: {} };
  new Function('window', src)(sandbox.window);
  return sandbox.window.__automataStability;
}

/// Names a machine produced. Every one of these was seen on a real page.
const GENERATED = {
  'ti6dpd': 'Google, the id healed onto the search box — different on every page load',
  'gLFyf': 'Google, the class beside it',
  'css-1a2b3c': 'emotion',
  'sc-bdVaJa': 'styled-components',
  'jsx-1234567890': 'styled-jsx',
  'svelte-1a2b3c': 'svelte scoping',
  'ember1234': 'Ember view counter',
  'radix-:r0:': 'Radix, generated id',
  ':r7:': 'React useId',
  '_xY3kQ': 'CSS modules, hash as the whole name',
  'react-aria-12': 'React Aria',
  'headlessui-menu-button-1': 'Headless UI',
  'a1b2c3d4': 'hex-shaped run',
  'x9zqpv': 'no vowels to speak of, a digit in the middle',
};

/// Names a person chose. Rejecting one of these is the expensive failure: it throws away the
/// strongest strategy in the cascade for an element that was perfectly identifiable.
const AUTHORED = [
  'search',        // Google's results container, and the fixture's own
  'b_results',     // Bing's results list
  'sb_form_q',     // Bing's search box
  'alpha', 'beta', 'gamma',
  'place-order', 'gamma-was-here',
  'nav2', 'tab1', 'h3',           // people number things, and put the number at the end
  'btn', 'row', 'log', 'tree',
  'main-content', 'site-header',
  'MuiButton-root',               // generated by a library, but stable across builds
  'navBar', 'myButton',           // camelCase is a choice
  'ed-harvest-pick-row',
  'product', 'results', 'invoices',
];

const STATE = ['is-open', 'has-error', 'js-toggle', 'active', 'selected', 'hover', 'expanded'];

const stability = loadStability();

group('names: every generated one is rejected', () => {
  const kept = Object.keys(GENERATED).filter((n) => !stability.looksGenerated(n));
  assertEqual(JSON.stringify(kept), '[]',
    `these would be recorded as identity: ${kept.map((n) => `${n} (${GENERATED[n]})`).join(', ')}`);
});

group('names: every authored one survives', () => {
  const lost = AUTHORED.filter((n) => stability.looksGenerated(n));
  assertEqual(JSON.stringify(lost), '[]',
    `these are names a person chose and the filter threw them away: ${lost.join(', ')}`);
});

group('names: a state class is not identity', () => {
  const missed = STATE.filter((n) => !stability.isStateClass(n));
  assertEqual(JSON.stringify(missed), '[]', `not recognised as state: ${missed.join(', ')}`);
  // and they are dropped from a class list, which is what the two callers actually ask for
  const kept = stability.stableClasses(['product', 'is-open', 'selected', 'css-1a2b3c', 'tile']);
  assertEqual(kept.join(','), 'product,tile', 'stableClasses kept something it should not have');
});

group('names: stableId hands back null rather than a generated id', () => {
  assertEqual(stability.stableId('ti6dpd'), null, 'a generated id must not be recorded');
  assertEqual(stability.stableId('search'), 'search', 'an authored id must be kept');
  assertEqual(stability.stableId(''), null, 'an absent id is not an id');
});

// ---- half two: elements ------------------------------------------------------------------------

const fixture = `<!doctype html>
<html><head><meta charset="utf-8"><title>Automata verify-js fixture</title></head>
<body>
  <h1>Names worth keeping, and names not</h1>

  <!-- The shape that started this: an authored name nowhere, a generated one on the element, and
       the only durable identity being the accessible name. -->
  <form>
    <textarea id="ti6dpd" class="gLFyf" name="q" role="combobox" aria-label="Search"></textarea>
    <button id="place-order" class="btn is-active">Place order</button>
  </form>

  <ul class="results">
    <li class="product css-1a2b3c" data-sku="aaa"><span class="title">First</span></li>
    <li class="product css-9f8e7d selected" data-sku="bbb"><span class="title">Second</span></li>
    <li class="product css-4c3b2a" data-sku="ccc"><span class="title">Third</span></li>
  </ul>
</body></html>`;

async function waitForHttp200(port, label, timeoutMs = 60000) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    try {
      const res = await fetch(`http://127.0.0.1:${port}/json/version`);
      if (res.ok) return;
    } catch { /* not up yet */ }
    await sleep(250);
  }
  throw new Error(`${label} never answered on :${port}`);
}

async function main() {
  const exePath = path.join(repoRoot, 'Automata.App', 'bin', 'Debug', 'net10.0-windows', 'Automata.App.exe');
  if (!existsSync(exePath)) {
    console.error(`App not built: ${exePath}\nRun: dotnet build -c Debug --nologo`);
    process.exit(2);
  }

  const scratch = path.join(tmpdir(), `automata-js-${randomUUID().slice(0, 8)}`);
  mkdirSync(scratch, { recursive: true });
  const fixturePath = path.join(scratch, 'fixture.html');
  writeFileSync(fixturePath, fixture);
  const fixtureUrl = 'file:///' + fixturePath.replace(/\\/g, '/');

  const proc = spawn(exePath, [], {
    cwd: path.dirname(exePath),
    env: {
      ...process.env,
      AUTOMATA_PANEL_CDP_PORT: String(PANEL_PORT),
      AUTOMATA_TARGET_CDP_PORT: String(TARGET_PORT),
      AUTOMATA_PANEL_PROFILE_DIR: path.join(scratch, 'panel-profile'),
      AUTOMATA_TARGET_PROFILE_DIR: path.join(scratch, 'target-profile'),
      AUTOMATA_COLLECTIONS_ROOT: path.join(scratch, 'collections'),
      AUTOMATA_DATASETS_ROOT: path.join(scratch, 'datasets'),
      AUTOMATA_RUNS_ROOT: path.join(scratch, 'runs'),
      AUTOMATA_SCHEDULE_PATH: path.join(scratch, 'schedule.json'),
      AUTOMATA_PARKED_ROOT: path.join(scratch, 'parked'),
      AUTOMATA_LIVE_ROOT: path.join(scratch, 'live'),
      AUTOMATA_DEMOS_ROOT: path.join(scratch, 'demos'),
      AUTOMATA_SETTINGS_PATH: path.join(scratch, 'settings.json'),
    },
    stdio: 'ignore',
  });

  let browser;
  try {
    // Both ports, because the app navigates its target pane once during startup and arriving
    // mid-navigation destroys the execution context out from under the first evaluate.
    await waitForHttp200(TARGET_PORT, 'target CDP endpoint');
    await waitForHttp200(PANEL_PORT, 'panel CDP endpoint');
    browser = await chromium.connectOverCDP(`http://127.0.0.1:${TARGET_PORT}`);
    const page = browser.contexts()[0].pages()[0];

    // Exactly what FingerprintResolver builds: stability first, then the script that leans on it.
    const bundle = ['stability.js', 'fingerprint.js', 'resolver.js', 'harvest.js']
      .map((f) => readFileSync(path.join(scriptsDir, f), 'utf8')).join('\n');

    let ready = false;
    for (let attempt = 0; attempt < 10 && !ready; attempt++) {
      try {
        await page.goto(fixtureUrl, { waitUntil: 'domcontentloaded' });
        await page.evaluate(bundle);
        ready = await page.evaluate(() => typeof window.__automataFingerprint === 'function');
      } catch { await sleep(500); }
    }
    assertTrue(ready, 'the fixture never held still long enough to inject into');

    await groupAsync('elements: a generated id and class are left out of the fingerprint', async () => {
      const fp = await page.evaluate(() =>
        window.__automataFingerprint(document.querySelector('textarea')));
      assertEqual(fp.id ?? null, null, 'the generated id was recorded as identity');
      assertEqual(JSON.stringify(fp.classList), '[]', 'the generated class was recorded');
      // What is left is what actually identifies it — and it is enough.
      assertEqual(fp.nameAttr, 'q', 'the name attribute is the durable part and must survive');
      assertEqual(fp.ariaLabel, 'Search', 'the accessible name must survive');
      assertTrue(!/ti6dpd/.test(fp.cssSelector ?? ''),
        `the selector was built from the generated id: ${fp.cssSelector}`);
    });

    await groupAsync('elements: an authored id is recorded, and is the selector', async () => {
      const fp = await page.evaluate(() =>
        window.__automataFingerprint(document.getElementById('place-order')));
      assertEqual(fp.id, 'place-order', 'an authored id must be kept');
      assertEqual(fp.cssSelector, '#place-order', 'and used as the selector');
      assertEqual(JSON.stringify(fp.classList), '["btn"]',
        'the state class should be dropped and the real one kept');
    });

    // The point of the whole exercise: what the filter leaves behind still resolves.
    await groupAsync('elements: the fingerprint left behind still finds the element', async () => {
      // The fingerprint goes in as an OBJECT — the engine interpolates its JSON straight into the
      // call, so what the function receives is a literal, never a string to parse.
      const answer = await page.evaluate(() => {
        const fp = window.__automataFingerprint(document.querySelector('textarea'));
        return JSON.parse(window.__automataResolve(fp, {}));
      });
      assertTrue(answer.found, `the filtered fingerprint no longer resolves: ${JSON.stringify(answer)}`);
      assertTrue(!answer.ambiguous, 'it resolved, but ambiguously');
    });

    // A heal writes back whatever __automataFingerprint returns, so this is the assertion that
    // stops a repair from making the record worse — the failure phase 29 found on Google.
    await groupAsync('elements: a refreshed fingerprint is filtered exactly like a recorded one', async () => {
      const refreshed = await page.evaluate(() => {
        const fp = window.__automataFingerprint(document.querySelector('textarea'));
        // Resolve by something OTHER than id/css, which is what makes the resolver refingerprint.
        const answer = JSON.parse(window.__automataResolve(
          { tag: 'textarea', nameAttr: 'q', ariaLabel: 'Search' },
          { refingerprint: true }));
        return { answer, recordedId: fp.id ?? null };
      });
      assertTrue(refreshed.answer.found, 'the fallback resolve did not find it');
      const fp = refreshed.answer.refreshedFingerprint;
      assertTrue(fp != null, 'nothing was refreshed, so this check proves nothing');
      assertEqual(fp.id ?? null, null,
        `a heal wrote a generated id back into the record: ${fp.id}`);
      assertEqual(JSON.stringify(fp.classList), '[]', 'a heal wrote a generated class back');
    });

    await groupAsync('elements: a harvest generalises rows past their per-row hash classes', async () => {
      const picked = await page.evaluate(() =>
        JSON.parse(window.__automataPickSet(document.querySelector('li.product'))));
      assertTrue(picked.ok, `the pick failed: ${JSON.stringify(picked)}`);
      assertEqual(picked.count, 3,
        `one row should generalise to all three; the selector was ${picked.selector}`);
      assertTrue(!/css-/.test(picked.selector),
        `the row selector kept a per-row hash class: ${picked.selector}`);
    });

    await groupAsync('elements: the same filter answers for a harvest and a fingerprint', async () => {
      const both = await page.evaluate(() => {
        const el = document.querySelector('li.product.selected');
        return {
          fingerprint: window.__automataFingerprint(el).classList,
          stable: window.__automataStability.stableClasses(el.classList),
        };
      });
      assertEqual(JSON.stringify(both.fingerprint), JSON.stringify(both.stable),
        'the two callers disagreed about the same element, which is the drift this file exists to stop');
    });
  } finally {
    try { await browser?.close(); } catch { /* already gone */ }
    const exited = new Promise((resolve) => proc.once('exit', resolve));
    proc.kill();
    if (!keep) {
      await Promise.race([exited, sleep(5000)]);
      for (let attempt = 0; attempt < 5; attempt++) {
        try { rmSync(scratch, { recursive: true, force: true }); break; }
        catch { await sleep(1000); }
      }
    } else {
      console.log(`\nScratch kept: ${scratch}`);
    }
  }
}

await main();

const passed = results.filter((r) => r.ok).length;
console.log(`RESULT: ${passed}/${results.length} passed`);
process.exitCode = passed === results.length ? 0 : 1;
